DROP TABLE IF EXISTS professor_subject CASCADE;
DROP TABLE IF EXISTS student_rating CASCADE;
DROP TABLE IF EXISTS student CASCADE;
DROP TABLE IF EXISTS group_ CASCADE;
DROP TABLE IF EXISTS rate CASCADE;
DROP TABLE IF EXISTS professor CASCADE;
DROP TABLE IF EXISTS subject CASCADE;